language: php

dist: trusty

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  
install: composer install -n

before_script: 
  - composer require satooshi/php-coveralls:1.* -n
  # need to enable xdebug in hhvm for code coverage
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi

script: ./vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - travis_retry ./vendor/bin/coveralls --coverage_clover=clover.xml
  # or enable logging
  - travis_retry ./vendor/bin/coveralls --coverage_clover=clover.xml -v